### ISSUE TITLE
Unleash changes

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-platform#972] opened 2024-06-21 13:53 UTC
- [x] Add app version as a context field value
- [x] Add os as context field value
- [x] users receiving multiple variants (stickiness not working as expected?) - solved?

  - https://metabase.bcc.media/question/700-userids-getting-multiple-variants

latest status: tested with app version >= 2300185 for this feature flag https://unleash-server-prod-t5xl3eo6wq-ez.a.run.app/projects/default/features/skip-to-chapter and the flag doesnt get applied

**Comment by andreasgangso** [comment] 2024-08-20 09:41
> * Add app version as a context field value
> * Add os as context field value
> * users receiving multiple variants (stickiness not working as expected?) - solved?
>   
>   * https://metabase.bcc.media/question/700-userids-getting-multiple-variants

Not happening after june 27th. See [modified query](https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJicmVha291dCI6W1siZmllbGQiLCJjb3VudF8yIix7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciJ9XV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkIiwiY291bnQiLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV0sInNvdXJjZS1xdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXSxbImRpc3RpbmN0IixbImV4cHJlc3Npb24iLCJFdmVudCBzZWN0aW9uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV1dLCJicmVha291dCI6W1siZmllbGQiLDc1NDU1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiZXhwcmVzc2lvbnMiOnsiUGxheXRpbWUgaG91cnMiOlsiLyIsWyJmaWVsZCIsNzU0NzgsbnVsbF0sMzYwMF0sIkV2ZW50IHNlY3Rpb24iOlsiY2FzZSIsW1tbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjplbmFibGVkIl0sIkV2ZW50IHNlY3Rpb24gZW5hYmxlZCJdLFtbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjpkaXNhYmxlZCJdLCJFdmVudCBTZWN0aW9uIGRpc2FibGVkIl1dLHsiZGVmYXVsdCI6Ik90aGVyIn1dfSwic291cmNlLXRhYmxlIjo0MDI3LCJmaWx0ZXIiOlsiYW5kIixbIj4iLFsiZmllbGQiLDc1NDY5LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLCIyMDI0LTA2LTI3Il0sWyI9IixbImZpZWxkIiw3NTQ3MyxudWxsXSwibW9iaWxlIiwiYmNjbS1tb2JpbGUiXSxbIj0iLFsiZmllbGQiLDc1NDc1LG51bGxdLCJWT0QiXSxbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbiIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XV19fX0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiZ3JhcGguc2hvd19nb2FsIjpmYWxzZSwiZ3JhcGguc2hvd190cmVuZGxpbmUiOnRydWUsImdyYXBoLnNob3dfdmFsdWVzIjpmYWxzZSwicGllLmRpbWVuc2lvbiI6IlFvdGQiLCJ0YWJsZS5jZWxsX2NvbHVtbiI6ImNvdW50IiwiZ3JhcGguc2VyaWVzX29yZGVyX2RpbWVuc2lvbiI6bnVsbCwiZ3JhcGgubWV0cmljcyI6WyJjb3VudF8yIiwiY291bnQiLCJzdW0iXSwiZ3JhcGguc2VyaWVzX29yZGVyIjpudWxsLCJwaWUubWV0cmljIjoic3VtIiwidGFibGUucGl2b3RfY29sdW1uIjoiY291bnRfMiIsInNlcmllc19zZXR0aW5ncyI6eyJzdW0iOnsiYXhpcyI6bnVsbCwiZGlzcGxheSI6ImJhciIsImxpbmUubWFya2VyX2VuYWJsZWQiOm51bGwsImxpbmUubWlzc2luZyI6Inplcm8ifX0sImdyYXBoLmRpbWVuc2lvbnMiOlsiZXZlbnRfdGltZSIsIkV2ZW50IHNlY3Rpb24iXSwic3RhY2thYmxlLnN0YWNrX3R5cGUiOm51bGx9LCJvcmlnaW5hbF9jYXJkX2lkIjo3MDB9)

**Comment by andreasgangso** [comment] 2024-08-20 09:54
### Analysis: Users receiving multiple variants
The following image is one of the users in your query that got 2 different "event section" values:
![Image](https://github.com/user-attachments/assets/1ec1cf1a-9925-427f-89d3-e7c9cf2904e9)

So the root cause is that a user could get "public featureflags" while logged in, because of inconsistencies between states in the app. 

I did a bunch of fixes for feature flags in v5.5.1: https://github.com/bcc-code/bcc-media-app/blob/master/CHANGELOG.md#5512300151-2024-06-11

And this seems to be fixed in v5.5.1, as no user with v5.5.1 or above had that issue ([see query](https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJicmVha291dCI6W1siZmllbGQiLCJjb3VudF8yIix7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciJ9XV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkIiwiY291bnQiLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV0sInNvdXJjZS1xdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXSxbImRpc3RpbmN0IixbImV4cHJlc3Npb24iLCJFdmVudCBzZWN0aW9uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV1dLCJicmVha291dCI6W1siZmllbGQiLDc1NDU1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiZXhwcmVzc2lvbnMiOnsiUGxheXRpbWUgaG91cnMiOlsiLyIsWyJmaWVsZCIsNzU0NzgsbnVsbF0sMzYwMF0sIkV2ZW50IHNlY3Rpb24iOlsiY2FzZSIsW1tbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjplbmFibGVkIl0sIkV2ZW50IHNlY3Rpb24gZW5hYmxlZCJdLFtbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjpkaXNhYmxlZCJdLCJFdmVudCBTZWN0aW9uIGRpc2FibGVkIl1dLHsiZGVmYXVsdCI6Ik90aGVyIn1dfSwic291cmNlLXRhYmxlIjo0MDI3LCJmaWx0ZXIiOlsiYW5kIixbIj0iLFsiZmllbGQiLDc1NDczLG51bGxdLCJtb2JpbGUiLCJiY2NtLW1vYmlsZSJdLFsiPSIsWyJmaWVsZCIsNzU0NzUsbnVsbF0sIlZPRCJdLFsiY29udGFpbnMiLFsiZmllbGQiLDc2MDQyLG51bGxdLCJldmVudC1zZWN0aW9uIix7ImNhc2Utc2Vuc2l0aXZlIjpmYWxzZX1dLFsiPSIsWyJmaWVsZCIsNzU0MzkseyJiYXNlLXR5cGUiOiJ0eXBlL1RleHQifV0sIjUuNS4xKzIzMDAxNTEiLCI1LjUuMisyMzAwMTUyIiwiNS41LjMrMjMwMDE1MyIsIjUuNS40KzIzMDAxNTQiLCI1LjUuNSsyMzAwMTU1IiwiNS41LjYrMjMwMDE1NiIsIjUuNS43KzIzMDAxNTciLCI1LjUuOCsyMzAwMTU4IiwiNS41LjkrMjMwMDE1OSJdXX19fSwiZGlzcGxheSI6InRhYmxlIiwiZGlzcGxheUlzTG9ja2VkIjp0cnVlLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJncmFwaC5zaG93X2dvYWwiOmZhbHNlLCJncmFwaC5zaG93X3RyZW5kbGluZSI6dHJ1ZSwiZ3JhcGguc2hvd192YWx1ZXMiOmZhbHNlLCJwaWUuZGltZW5zaW9uIjoiUW90ZCIsInRhYmxlLmNlbGxfY29sdW1uIjoiY291bnQiLCJncmFwaC5zZXJpZXNfb3JkZXJfZGltZW5zaW9uIjpudWxsLCJncmFwaC5tZXRyaWNzIjpbImNvdW50XzIiLCJjb3VudCIsInN1bSJdLCJncmFwaC5zZXJpZXNfb3JkZXIiOm51bGwsInBpZS5tZXRyaWMiOiJzdW0iLCJ0YWJsZS5waXZvdF9jb2x1bW4iOiJjb3VudF8yIiwic2VyaWVzX3NldHRpbmdzIjp7InN1bSI6eyJheGlzIjpudWxsLCJkaXNwbGF5IjoiYmFyIiwibGluZS5tYXJrZXJfZW5hYmxlZCI6bnVsbCwibGluZS5taXNzaW5nIjoiemVybyJ9fSwiZ3JhcGguZGltZW5zaW9ucyI6WyJldmVudF90aW1lIiwiRXZlbnQgc2VjdGlvbiJdLCJzdGFja2FibGUuc3RhY2tfdHlwZSI6bnVsbH0sIm9yaWdpbmFsX2NhcmRfaWQiOjcwMH0=), and [this one filtered on before 27th june to be extra sure](https://metabase.bcc.media/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo5LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJicmVha291dCI6W1siZmllbGQiLCJjb3VudF8yIix7ImJhc2UtdHlwZSI6InR5cGUvSW50ZWdlciJ9XV0sImFnZ3JlZ2F0aW9uIjpbWyJjb3VudCJdLFsic3VtIixbImZpZWxkIiwiY291bnQiLHsiYmFzZS10eXBlIjoidHlwZS9JbnRlZ2VyIn1dXV0sInNvdXJjZS1xdWVyeSI6eyJhZ2dyZWdhdGlvbiI6W1siY291bnQiXSxbImRpc3RpbmN0IixbImV4cHJlc3Npb24iLCJFdmVudCBzZWN0aW9uIix7ImJhc2UtdHlwZSI6InR5cGUvVGV4dCJ9XV1dLCJicmVha291dCI6W1siZmllbGQiLDc1NDU1LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dXSwiZXhwcmVzc2lvbnMiOnsiUGxheXRpbWUgaG91cnMiOlsiLyIsWyJmaWVsZCIsNzU0NzgsbnVsbF0sMzYwMF0sIkV2ZW50IHNlY3Rpb24iOlsiY2FzZSIsW1tbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjplbmFibGVkIl0sIkV2ZW50IHNlY3Rpb24gZW5hYmxlZCJdLFtbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbjpkaXNhYmxlZCJdLCJFdmVudCBTZWN0aW9uIGRpc2FibGVkIl1dLHsiZGVmYXVsdCI6Ik90aGVyIn1dfSwic291cmNlLXRhYmxlIjo0MDI3LCJmaWx0ZXIiOlsiYW5kIixbIjwiLFsiZmllbGQiLDc1NDY5LHsiYmFzZS10eXBlIjoidHlwZS9EYXRlVGltZVdpdGhMb2NhbFRaIn1dLCIyMDI0LTA2LTI3Il0sWyI9IixbImZpZWxkIiw3NTQ3MyxudWxsXSwibW9iaWxlIiwiYmNjbS1tb2JpbGUiXSxbIj0iLFsiZmllbGQiLDc1NDc1LG51bGxdLCJWT0QiXSxbImNvbnRhaW5zIixbImZpZWxkIiw3NjA0MixudWxsXSwiZXZlbnQtc2VjdGlvbiIseyJjYXNlLXNlbnNpdGl2ZSI6ZmFsc2V9XSxbIj0iLFsiZmllbGQiLDc1NDM5LHsiYmFzZS10eXBlIjoidHlwZS9UZXh0In1dLCI1LjUuMSsyMzAwMTUxIiwiNS41LjIrMjMwMDE1MiIsIjUuNS4zKzIzMDAxNTMiLCI1LjUuNCsyMzAwMTU0IiwiNS41LjUrMjMwMDE1NSIsIjUuNS42KzIzMDAxNTYiLCI1LjUuNysyMzAwMTU3IiwiNS41LjgrMjMwMDE1OCIsIjUuNS45KzIzMDAxNTkiXV19fX0sImRpc3BsYXkiOiJ0YWJsZSIsImRpc3BsYXlJc0xvY2tlZCI6dHJ1ZSwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnsiZ3JhcGguc2hvd19nb2FsIjpmYWxzZSwiZ3JhcGguc2hvd190cmVuZGxpbmUiOnRydWUsImdyYXBoLnNob3dfdmFsdWVzIjpmYWxzZSwicGllLmRpbWVuc2lvbiI6IlFvdGQiLCJ0YWJsZS5jZWxsX2NvbHVtbiI6ImNvdW50IiwiZ3JhcGguc2VyaWVzX29yZGVyX2RpbWVuc2lvbiI6bnVsbCwiZ3JhcGgubWV0cmljcyI6WyJjb3VudF8yIiwiY291bnQiLCJzdW0iXSwiZ3JhcGguc2VyaWVzX29yZGVyIjpudWxsLCJwaWUubWV0cmljIjoic3VtIiwidGFibGUucGl2b3RfY29sdW1uIjoiY291bnRfMiIsInNlcmllc19zZXR0aW5ncyI6eyJzdW0iOnsiYXhpcyI6bnVsbCwiZGlzcGxheSI6ImJhciIsImxpbmUubWFya2VyX2VuYWJsZWQiOm51bGwsImxpbmUubWlzc2luZyI6Inplcm8ifX0sImdyYXBoLmRpbWVuc2lvbnMiOlsiZXZlbnRfdGltZSIsIkV2ZW50IHNlY3Rpb24iXSwic3RhY2thYmxlLnN0YWNrX3R5cGUiOm51bGx9LCJvcmlnaW5hbF9jYXJkX2lkIjo3MDB9)).

**Comment by andreasgangso** [comment] 2024-08-20 10:09
doing this one @mulundapm

**Comment by andreasgangso** [comment] 2024-08-23 08:42
buildNumber is more useful that app version, since it is numeric.
Which means you can do
`appBuildNumber > 2300181`

**Comment by andreasgangso** [comment] 2024-08-23 08:43
not implemented for tvos

**Comment by andreasgangso** [comment] 2024-08-23 09:06
Implemented for tvos starting from v4.2.19

**Comment by mulundapm** [comment] 2024-09-02 09:47
tested with app version >= 2300185 for this feature flag https://unleash-server-prod-t5xl3eo6wq-ez.a.run.app/projects/default/features/skip-to-chapter and the flag doesnt get applied

**Comment by andreasgangso** [comment] 2024-09-28 12:46
> tested with app version >= 2300185 for this feature flag https://unleash-server-prod-t5xl3eo6wq-ez.a.run.app/projects/default/features/skip-to-chapter and the flag doesnt get applied

Ok so there's just a misunderstanding here.
You have two fields in unleash: appVersion and appBuildNumber.
appVersion: A not-numeric version number, e.g. 5.6.21+2300181. Cannot be used with numeric operators (GT, LT, etc)
appBuildNumber: Numeric increasing build number, e.g. 2300181. Can be used with numeric operators.
You can't use app version, you need to use appBuildNumber.
I confirmed that `appBuildNumber` works:

![Image](https://github.com/user-attachments/assets/0747b04e-e272-4972-a6f7-196b71d1f64d)

**Closed** 2024-09-28 12:47 UTC
Labels: help wanted
